name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Build AutoFlash"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: AutoFlash
          path: ./artifact

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./artifact

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './artifact'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Output Pages URL
        run: echo "Artifact is available at ${{ steps.deployment.outputs.page_url }}"